"""
intelligence.events.base
------------------------
Core data structures for the Event Intelligence layer.

Architecture principle (from context.md):
    Detection → Observation → Event → (multiple events) → Incident

This module defines:
    - EventType: All possible event classifications.
    - SurveillanceEvent: The normalized output of every event rule.

Rules:
    - A single detected object in a single frame is NEVER an event by itself.
    - An event requires temporal or spatial context (trajectory, time, zone).
    - All downstream code (risk engine, incident engine) consumes SurveillanceEvent.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Optional, Tuple


class EventType(Enum):
    """
    All possible event types generated by the Event Engine.
    Ordered roughly by severity (lower = more routine).
    """
    # Zone / Spatial events
    ZONE_ENTRY = auto()          # Object entered a defined restricted zone
    ZONE_EXIT = auto()           # Object exited a restricted zone
    LINE_CROSSING = auto()       # Object crossed a defined virtual fence line

    # Temporal / Behavioural events
    LOITERING = auto()           # Object lingered in a zone beyond the threshold

    # Direction
    WRONG_DIRECTION = auto()     # Object moving against the expected flow


class EventSeverity(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class SurveillanceEvent:
    """
    Normalized output of the Event Engine for a single detected event.

    All downstream systems (risk engine, incident engine, alert engine) consume
    this type exclusively. No rule-specific types appear outside this module.

    Attributes:
        event_type:   Classification of the event.
        severity:     Initial severity assessment.
        track_id:     Track ID of the object that triggered the event.
        camera_name:  Name of the camera that observed the event.
        timestamp:    Unix timestamp when the event occurred.
        frame_id:     Frame number when the event was triggered.
        location:     Pixel (x, y) coordinate where the event was triggered.
        class_name:   Object class (e.g., "person", "car").
        confidence:   Detection confidence of the triggering detection.
        rule_name:    Human-readable name of the rule that fired.
        details:      Optional freeform dict for rule-specific extras.
    """
    event_type: EventType
    severity: EventSeverity
    track_id: int
    camera_name: str
    timestamp: float
    frame_id: int
    location: Tuple[float, float]
    class_name: str
    confidence: float
    rule_name: str
    details: dict = field(default_factory=dict)

    def __repr__(self) -> str:
        ts = time.strftime("%H:%M:%S", time.localtime(self.timestamp))
        return (
            f"[{ts}] {self.event_type.name} | Track #{self.track_id} "
            f"({self.class_name}) | {self.severity.value.upper()} | {self.rule_name}"
        )
