"""intelligence.events.base — Event definitions."""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Tuple


class EventType(Enum):
    """All possible event types generated by the Event Engine."""
    # Zone / Spatial events
    ZONE_ENTRY = auto()
    ZONE_EXIT = auto()
    LINE_CROSSING = auto()

    # Temporal / Behavioural events
    LOITERING = auto()

    # Direction
    WRONG_DIRECTION = auto()

    # Phase 5: ANPR
    VEHICLE_ANPR = auto()

    # Phase 6: Night-time activity
    NIGHT_MOVEMENT = auto()


class EventSeverity(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class SurveillanceEvent:
    event_type: EventType
    severity: EventSeverity
    track_id: int
    camera_name: str
    timestamp: float
    frame_id: int
    location: Tuple[float, float]
    class_name: str
    confidence: float
    rule_name: str
    details: dict = field(default_factory=dict)

    def __repr__(self) -> str:
        ts = time.strftime("%H:%M:%S", time.localtime(self.timestamp))
        return (
            f"[{ts}] {self.event_type.name} | Track #{self.track_id} "
            f"({self.class_name}) | {self.severity.value.upper()} | {self.rule_name}"
        )
